version: '3.9'
services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=forecast_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  streamlit:
    image: python:3.10
    container_name: streamlit_app
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8501:8501"
    command: sh -c "pip install -r requirements.txt && streamlit run streamlit_app/dashboard.py"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: forecast_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: